version: '3'

services:
    api:
        build:
            context: .
            dockerfile: api.Dockerfile
        container_name: youtube-like-api
        networks:
            - youtube-like-network
        command: dockerize -wait tcp://mysql:3306 -timeout 60s yarn start:api
        working_dir: /usr/src/api
        user: node
        depends_on:
            - mysql
        volumes:
            - $PWD:/usr/src/api
        ports:
            - $API_PORT:$API_PORT

    pwa:
        image: node:16
        container_name: youtube-like-pwa
        networks:
            - youtube-like-network
        command: yarn start:pwa
        working_dir: /usr/src/pwa
        user: node
        depends_on:
            - mysql
        volumes:
            - $PWD:/usr/srcnew/pwa
        ports:
            - $PWA_PORT:3000

    mysql:
        image: mysql:5.7
        container_name: youtube-like-mysql
        networks:
            - youtube-like-network
        env_file: .env

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5
        container_name: youtube-like-phpmyadmin
        networks:
            - youtube-like-network
        depends_on:
            - mysql
        environment:
            PMA_HOST: youtube-like-mysql
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        ports:
            - $PMA_PORT:80

networks:
    youtube-like-network:
        driver: bridge
