version: '3'

services:
    api:
        image: node:16
        container_name: youtube-like-api
        command: yarn start:api
        working_dir: /usr/src/api
        user: node
        volumes:
            - $PWD:/usr/src/api
        ports:
            - $API_PORT:$API_PORT
    
    pwa:
        image: node:16
        container_name: youtube-like-pwa
        command: yarn start:pwa
        working_dir: /usr/src/pwa
        volumes:
            - $PWD:/usr/src/pwa
        ports:
            - $PWA_PORT:$PWA_PORT
