version: '3'

services:
    api:
        image: node:16-alpine
        container_name: youtube-like-api
        command: yarn serve:api
        working_dir: /usr/src/api
        user: node
        env_file: .env
        depends_on:
            - mysql
        volumes:
            - $PWD:/usr/src/api

    pwa:
        image: node:16-alpine
        container_name: youtube-like-pwa
        command: yarn serve:pwa
        working_dir: /usr/src/pwa
        user: node
        env_file: .env
        depends_on:
            - api
        volumes:
            - $PWD:/usr/src/pwa
        ports:
            - $PWA_PORT:$PWA_PORT

    mysql:
        image: mysql:5.7
        container_name: youtube-like-mysql
        env_file: .env

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5
        container_name: youtube-like-phpmyadmin
        depends_on:
            - mysql
        environment:
            PMA_HOST: youtube-like-mysql
            MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        ports:
            - $PMA_PORT:80
