version: '3'

services:
    api:
        image: node:16-alpine
        working_dir: /usr/src/api
        environment:
            NODE_ENV: production
        volumes:
            - $PWD:/usr/src/api
        command: node dist/api/main.js main.js
        ports:
            - ${API_PORT}:${API_PORT}

    pwa:
        image: httpd:alpine3.15
        volumes:
            - $PWD/dist/pwa:/usr/local/apache2/htdocs
        ports:
            - ${PWA_PORT}:80