version: '3'

services:
    api:
        image: node:16-alpine
        working_dir: /usr/src/api
        depends_on:
            - mysql
        environment:
            NODE_ENV: production
            API_PORT: ${API_PORT}
            API_SECRET: ${API_SECRET}
            MYSQL_HOST: ${MYSQL_HOST}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - $PWD:/usr/src/api
        command: node dist/api/main.js main.js
        ports:
            - ${API_PORT}:${API_PORT}

    pwa:
        image: httpd:alpine3.15
        depends_on:
            - api
        volumes:
            - $PWD/dist/pwa:/usr/local/apache2/htdocs
        ports:
            - ${PWA_PORT}:80

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
